
services:
  - type: web
    name: telegram-bot-web
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r render_requirements.txt
    startCommand: python3 -m gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --preload render_web:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PORT
        sync: false
    healthCheckPath: /
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1
    
  - type: worker
    name: telegram-bot-service
    env: python
    region: oregon  
    plan: free
    buildCommand: pip install -r render_requirements.txt
    startCommand: python3 render_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
    disk:
      name: data
      mountPath: /opt/render/project/src  
      sizeGB: 1
